### ISSUE TITLE
No production canister_ids.json found.

### ISSUE THREAD

**Issue by CleoPatra2772** [dfinity/sdk#2261]
When I entered npm start I get an error that says: 

No production canister_ids.json found. Continuing with local

[webpack-cli] TypeError: cli.isMultipleCompiler is not a function

    at Command.<anonymous> (/Users/cleogao/IC-Projects/hello/node_modules/@webpack-cli/serve/lib/index.js:146:35)

    at async Promise.all (index 1)

    at async Command.<anonymous> (/Users/cleogao/IC-Projects/hello/node_modules/webpack-cli/lib/webpack-cli.js:1672:7)

my npm verison is 8.5.5

my node verison is 16.5.0 (I used a 14.0.0 version it gave me more errors)

and my dfx is 0.9.3

I tried to change webpack to 4.10.0 but that doesnt work either...

please helpp

**Comment by CleoPatra2772** [comment]
changed webpack-cli to 4.10.0 problem sovled
